### ISSUE TITLE
Code-splitting ckeditor style and js - embed css without js

### ISSUE THREAD

**Issue by MartinMuzatko** [ckeditor/ckeditor4#2781]
## Type of report

Feature request

## Provide description of the new feature

The problem right now, is that I have to load the complete editor, to style the `.ck-content` elements.
It would be nice to be able to make use of code-splitting and only load the CSS for the generated HTML.
This way, only editors have to load the ckeditor js code and readers only load the CSS for displaying the HTML correctly.

I haven't found a way yet to do that.

**Comment by Comandeer** [comment]
The basic styles for editor's content is located inside [`contents.css` file](http://cdn.ckeditor.com/4.11.1/standard-all/contents.css), however many plugins embed CSS directly into HTML, via [`CKEDITOR.addCss` method](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-addCss). This feature would probably require rewriting the whole logic of handling CSS in CKE4.

**Comment by MartinMuzatko** [comment]
For now i hand-picked the CSS that was generated during runtime, required to render the content properly.
It is not beautiful, but better than having to load the entire ckeditor css :/

I found that with the contents.css file you referenced, there is barely an overlap with what I found.

``` css
.ck-content blockquote {
  overflow: hidden;
  padding-right: 1.5em;
  padding-left: 1.5em;
  margin-left: 0;
  font-style: italic;
  border-left: 5px solid #ccc;
}
.ck-content .image {
  clear: both;
  text-align: center;
  position: relative;
  overflow: hidden;
}
.ck-content .image img {
  display: block;
  margin: 0 auto;
  max-width: 100%;
}
.ck-content .image figcaption {
  color: #333;
  background-color: #f7f7f7;
  padding: 0.6em;
  font-size: 0.75em;
  outline-offset: -1px;
}
.ck-content .image-style-align-center,
.ck-content .image-style-align-left,
.ck-content .image-style-align-right,
.ck-content .image-style-side {
  max-width: 50%;
}
.ck-content .image-style-side {
  float: right;
  margin-left: 1.5em;
}
.ck-content .image-style-align-left {
  float: left;
  margin-right: 1.5em;
}
.ck-content .image-style-align-center {
  margin-left: auto;
  margin-right: auto;
}
.ck-content .image-style-align-right {
  float: right;
  margin-left: 1.5em;
}
```
